const barriosBarcelona = [
  "Baró de Viver",
  "Can Baró",
  "Can Peguera",
  "Canyelles",
  "Ciutat Meridiana",
  "Diagonal Mar i el Front Marítim del Poblenou",
  "Horta",
  "Hostafrancs",
  "Montbau",
  "Navas",
  "Pedralbes",
  "Porta",
  "Provençals del Poblenou",
  "Sant Andreu",
  "Sant Antoni",
  "Sant Genís dels Agudells",
  "Sant Gervasi- Galvany",
  "Sant Gervasi- la Bonanova",
  "Sant Martí de Provençals",
  "Sant Pere, Santa Caterina i la Ribera",
  "Sants",
  "Sants-Badal",
  "Sarrià",
  "Torre Baró",
  "Vallbona",
  "Vallcarca i els Penitents",
  "Vallvidrera, el Tibidabo i les Planes",
  "Verdun",
  "Vilapicina i la Torre Llobeta",
  "el Baix Guinardó",
  "el Barri Gòtic",
  "el Besòs i el Maresme",
  "el Bon Pastor",
  "el Camp d'en Grassot i Gràcia Nova",
  "el Camp de l'Arpa del Clot",
  "el Carmel",
  "el Clot",
  "el Coll",
  "el Congrés i els Indians",
  "el Fort Pienc",
  "el Guinardó",
  "el Parc i la Llacuna del Poblenou",
  "el Poble Sec",
  "el Poblenou",
  "el Putxet i el Farró",
  "el Raval",
  "el Turó de la Peira",
  "l'Antiga Esquerra de l'Eixample",
  "la Barceloneta",
  "la Bordeta",
  "la Clota",
  "la Dreta de l'Eixample",
  "la Font d'en Fargues",
  "la Font de la Guatlla",
  "la Guineueta",
  "la Marina de Port",
  "la Marina del Prat Vermell",
  "la Maternitat i Sant Ramon",
  "la Nova Esquerra de l'Eixample",
  "la Prosperitat",
  "la Sagrada Família",
  "la Sagrera",
  "la Salut",
  "la Teixonera",
  "la Trinitat Nova",
  "la Trinitat Vella",
  "la Vall d'Hebron",
  "la Verneda i la Pau",
  "la Vila Olímpica del Poblenou",
  "la Vila de Gràcia",
  "les Corts",
  "les Roquetes",
  "les Tres Torres"
];
export default barriosBarcelona;